version: "3.7"
name: bulkunsubscribe
services:
  bulkunsubscribe:
    image: bulkunsubscribe
    ports:
      - "80:8080"
    volumes:
      - ./sqlite:/app/sqlite
    container_name: bulkunsubscribe
    restart: unless-stopped
    env_file:
      - "./.env"
